steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/video-combiner', '.']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'video-combiner',
      '--image', 'gcr.io/$PROJECT_ID/video-combiner',
      '--platform', 'managed',
      '--region', 'us-central1',
      '--memory', '4Gi',
      '--timeout', '900',
      '--allow-unauthenticated'
    ]

images:
  - 'gcr.io/$PROJECT_ID/video-combiner'

logsBucket: gs://mineral-trainer-462918-i9-build-logs
